### PR TITLE
Feature/express server

### LINKED ISSUE #1: Initial Backend
## Create initial backend using Node.js and Express

### PR DESCRIPTION
**Pull request by marshalldanel**
Created basic express server to get backend up and running

### CODE REVIEW

**Comment by mawarijo** [comment]
Looks fine for the basic setup. Just a couple nitpicks:
- could we move eslint to devDependencies?
- also, can nodemon be added as a devDependency instead of relying on a global install?
- you've added eslint as a dependency but I don't see an eslint config file?
- can we add prettier + eslint-plugin-prettier + eslint-config-prettier and get it all set up?

Otherwise should be fine!

**Comment by marshalldanel** [comment]
Yes will add and move all to devDependencies. VS Code has spoiled me!

**Comment by mawarijo** [comment]
Thanks! I understand about getting spoiled, but it'll make sure our configurations match so we don't go back and forth replacing each other's styles. XD

**Comment by mawarijo** [comment]
Thanks for all the changes. Approving and merging.

**Pull request merged**
